{"date": 1977, text: "Mariner Jupiter/Saturn 1977 is renamed Voyager"},
{"date": 1977-8-20, text: "Voyager 2 launched from Kennedy Space Flight Center"},
{"date": 1977-9-5, text: "Voyager 1 launched from Kennedy Space Flight Center. Voyager 1 returns first spacecraft photo of Earth and Moon"},
{"date": 1979-3-5, text: "Voyager 1 makes its closest approach to Jupiter"},
{"date": 1979-7-9, text: "Voyager 2 makes its closest approach to Jupiter"},
{"date": 1980-11-12, text: "Voyager 1 flies by Saturn. Voyager 1 begins its trip out of the Solar System"},
{"date": 1981-8-25, text: "Voyager 2 flies by Saturn"},
{"date": 1982, text: "Deep Space Network upgrades two 26-m antennas to 34-m"},
{"date": 1986-1-24, text: "Voyager 2 has the first-ever encounter with Uranus. Deep Space Network begins expansion of 64-m antennas to 70-m"},
{"date": 1987, text: 'Voyager 2 "observes" Supernova 1987A'},
{"date": 1988, text: "Voyager 2 returns first color images of Neptune"},
{"date": 1989-8-25, text: "Voyager 2 is the first spacecraft to observe Neptune. Voyager 2 begins its trip out of the Solar System below the ecliptic plane"},
{"date": 1990-1-1, text: "Begins Voyager Interstellar Mission"},
{"date": 1990-2-14, text: "Last Voyager Images - Portrait of the Solar System"},
{"date": 1998-2-17, text: "Voyager 1 passes Pioneer 10 to become the most distant human-made object in space"},
{"date": 2004-12-15, text: "Voyager 1 crosses Termination Shock"},
{"date": 2007-9-5, text: "Voyager 2 crosses Termination Shock"};
